apiVersion: v1
kind: Secret
metadata:
  name: titan-backend-secret
  namespace: titan
  labels:
    app.kubernetes.io/name: titan-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: project-titan
type: Opaque
stringData:
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
