apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: titan-frontend
  namespace: titan
  labels:
    app.kubernetes.io/name: titan-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: project-titan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: titan-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
