server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:database}:${DB_PORT:3306}/${DB_NAME:student_db}?createDatabaseIfNotExist=true&sslMode=REQUIRED&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:rushi}
spring.datasource.password=${DB_PASSWORD:rushi123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
