-- Keep schema/table DDL here if needed.
-- The MariaDB Docker entrypoint already creates the database and user
-- from MYSQL_DATABASE/MYSQL_USER (or MARIADB_DATABASE/MARIADB_USER),
-- so avoid CREATE DATABASE / CREATE USER statements in this file.
